### ISSUE TITLE
I lost a MaterialFunction in the MaterialFunction called MF_FluidNinjaFX

### ISSUE THREAD

**Issue by baekhi** [Sartaq12/WaterInteractionPlugin#19]
UE 5.1.1
![Snipaste_2023-11-29_17-39-50](https://github.com/Sartaq12/WaterInteractionPlugin/assets/78615352/3d870092-1ab1-40f6-a862-ddc23ec30b97)
![Snipaste_2023-11-29_17-40-46](https://github.com/Sartaq12/WaterInteractionPlugin/assets/78615352/5da1681d-85b6-4a4d-8a82-931e1475e54b)

**Comment by Sartaq12** [comment]
You need FluidNinjaLIVE 1.9.51 that material function is only on the latest version
