### ISSUE TITLE
Can't build plugin in fresh 5.1.1 c++ project

### ISSUE THREAD

**Issue by ftorghele** [Sartaq12/WaterInteractionPlugin#5]
Hey Marin! First of all thanks for your effort integrating Fluid Ninja and Oceanology! I was doing my own solution few months ago (also with your help if you remember) but yours always looked better so I wanted to give it a try today.

I have a fresh 5.1.1 cpp project with only Oceanology enabled and Fluid Ninja migrated. As soon as I add your plugin (I copied the subfolder to the game's plugin folder) I can't start it anymore because it always tells me to rebuild the plugin which does not work (not "directly" from the engines dialogue and also not when I try to build using Visual Studio).

From what I can see it just does nothing. In VS it looks like the plugin would not be part of the compilation?

Here the log from within unreal:

> LogInit: Warning: Incompatible or missing module: WaterInteractionPlugin
Running P:/Unreal/UE_5.1/Engine/Build/BatchFiles/Build.bat Development Win64 -Project="P:/Prototypes/UF/UF.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" Development Win64 -Project="P:/Prototypes/UF/UF.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Log file: C:\Users\ft\AppData\Local\UnrealBuildTool\Log.txt
Invalidating makefile for UFEditor (WaterInteractionPlugin.Build.cs modified)
@progress push 5%
@progress pop
Building UFEditor...
Using Visual Studio 2019 14.29.30148 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
  Executing up to 12 processes, one per physical core
Building 1 action with 1 process...
[1/1] WriteMetadata UFEditor.target
Total time in Parallel executor: 0.23 seconds
Total execution time: 2.96 seconds
LogInit: Warning: Still incompatible or missing module: WaterInteractionPlugin

Here the log when I rebuild in VS:
> Rebuild started...
1>------ Rebuild All started: Project: UF, Configuration: Development_Editor x64 ------
1>Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UFEditor Win64 Development -Project="P:\Prototypes\UF\UF.uproject" -WaitMutex -FromMsBuild -Rebuild
1>Log file: C:\Users\ft\AppData\Local\UnrealBuildTool\Log.txt
1>Cleaning UFEditor and UnrealHeaderTool binaries...
1>Creating makefile for UFEditor (no existing makefile)
1>Parsing headers for UFEditor
1>  Running Internal UnrealHeaderTool P:\Prototypes\UF\UF.uproject P:\Prototypes\UF\Intermediate\Build\Win64\UFEditor\Development\UFEditor.uhtmanifest -WarningsAsErrors -installed
1>Total of 4 written
1>Reflection code generated for UFEditor in 0.8768485 seconds
1>Building UFEditor...
1>Using Visual Studio 2019 14.29.30148 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
1>  Executing up to 12 processes, one per physical core
1>Building 9 actions with 9 processes...
1>[1/9] Resource Default.rc2
1>[2/9] Compile SharedPCH.Engine.ShadowErrors.cpp
1>[3/9] Compile UF.init.gen.cpp
1>[4/9] Compile UF.cpp
1>[5/9] Compile UFGameModeBase.cpp
1>[6/9] Compile UFGameModeBase.gen.cpp
1>[7/9] Link UnrealEditor-UF.lib
1>   Bibliothek "P:\Prototypes\UF\Intermediate\Build\Win64\UnrealEditor\Development\UF\UnrealEditor-UF.lib" und Objekt "P:\Prototypes\UF\Intermediate\Build\Win64\UnrealEditor\Development\UF\UnrealEditor-UF.exp" werden erstellt.
1>[8/9] Link UnrealEditor-UF.dll
1>   Bibliothek "P:\Prototypes\UF\Intermediate\Build\Win64\UnrealEditor\Development\UF\UnrealEditor-UF.suppressed.lib" und Objekt "P:\Prototypes\UF\Intermediate\Build\Win64\UnrealEditor\Development\UF\UnrealEditor-UF.suppressed.exp" werden erstellt.
1>[9/9] WriteMetadata UFEditor.target
1>Total time in Parallel executor: 42.48 seconds
1>Total execution time: 45.87 seconds
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by Sartaq12** [comment]
Hello, I'm sorry you're experiencing some difficulties and thank you for bringing this up to my attention.
It's quite possible we talked on the discord, although maybe you don't have the same discord username as on github so I don't recall exactly unfortunately.

> rebuild the plugin which does not work (not "directly" from the engines dialogue and **also not when I try to build using Visual Studio**).
So you can't open the project with my plugin enabled, but in VS log there's also this line
> ========== Rebuild All: **1 succeeded**, 0 failed, 0 skipped ==========
Is there anything else that fails after that?

I have tried and failed to reproduce the issue.
I would like to list my steps here and could you please attempt them also to establish if that works.

1. Open a new Games/Blank C++ UE5.1.1 project ![image](https://user-images.githubusercontent.com/37218094/233844943-e4bf5dad-83ec-4fa2-8192-f25fd3be28a4.png)
2. Copy my plugin into it's Plugins folder  ![image](https://user-images.githubusercontent.com/37218094/233845016-d59febc0-773d-4a04-a1ba-5ac2f39b1107.png)
3. Copy or Migrate a fresh new FluidNinjaLIVE into it's Content folder  ![image](https://user-images.githubusercontent.com/37218094/233845157-13fba00b-d388-48df-8893-419a2703d6b1.png)
4. Open the project

This process works for me, I would be curious if it also works for you?

**Comment by Sartaq12** [comment]
@ftorghele could you please confirm this fix works for you?

**Comment by ftorghele** [comment]
Seems to fix the issue, thx!
